spring.application.name=ordermatchingengine

spring.datasource.url=jdbc:postgresql://localhost:5432/ordermatchingengine
spring.datasource.username=ordermatchingengine
spring.datasource.password=ordermatchingengine

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
