package com.nicholasp.ordermatchingengine.service;

import com.nicholasp.ordermatchingengine.engine.OrderBook;
import com.nicholasp.ordermatchingengine.model.Order;
import com.nicholasp.ordermatchingengine.model.OrderSide;
import com.nicholasp.ordermatchingengine.model.Trade;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.List;

/**
 * Application-facing entry point to the order matching engine.
 * <p>
 * Owns the single, shared {@link OrderBook} instance for the whole
 * application (Spring manages this class as a singleton bean, so every
 * request injected with it operates on the same book). Responsible for
 * turning raw request data into a valid domain {@link Order} before
 * delegating to the engine - the Controller layer should never construct
 * an {@link Order} itself.
 */
@Service
public class OrderBookService {

    private final OrderBook orderBook;

    public OrderBookService()
    {
        this.orderBook = new OrderBook();
    }

    /**
     * Builds an order from raw request values and submits it to the book.
     *
     * @param side the side of the order (BUY or SELL)
     * @param price the limit price
     * @param quantity the quantity requested
     * @return the trades generated by this submission, in execution order
     */
    public List<Trade> placeOrder(OrderSide side, BigDecimal price, long quantity)
    {
        Order order = new Order(side, price, quantity);
        return orderBook.submitOrder(order);
    }
}
