package com.nicholasp.ordermatchingengine.service;

import com.nicholasp.ordermatchingengine.engine.OrderBook;
import com.nicholasp.ordermatchingengine.model.Order;
import com.nicholasp.ordermatchingengine.model.OrderSide;
import com.nicholasp.ordermatchingengine.model.Trade;
import com.nicholasp.ordermatchingengine.repository.TradeEntity;
import com.nicholasp.ordermatchingengine.repository.TradeRepository;

import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Application-facing entry point to the order matching engine.
 * <p>
 * Owns the single, shared {@link OrderBook} instance for the whole
 * application (Spring manages this class as a singleton bean, so every
 * request injected with it operates on the same book). Responsible for
 * turning raw request data into a valid domain {@link Order} before
 * delegating to the engine - the Controller layer should never construct
 * an {@link Order} itself.
 */
@Service
public class OrderBookService {

    private final OrderBook orderBook;
    private final TradeRepository tradeRepository;
    private final SimpMessagingTemplate messagingTemplate;

    public OrderBookService(TradeRepository tradeRepository, SimpMessagingTemplate messagingTemplate)
    {
        this.orderBook = new OrderBook();
        this.tradeRepository = tradeRepository;
        this.messagingTemplate = messagingTemplate;
    }

    

    /**
     * The outcome of placing an order: the id assigned to it (so it can
     * later be looked up or cancelled, matched or not) and whatever trades
     * resulted from submitting it.
     */
    public record PlaceOrderResult(UUID orderId, List<Trade> trades) {}

    /**
     * Builds an order from RAW request values and submits it to the book.
     *
     * @param side the side of the order (BUY or SELL)
     * @param price the limit price
     * @param quantity the quantity requested
     * @return the id of the placed order plus the trades generated by this submission
     */
    public PlaceOrderResult placeOrder(OrderSide side, BigDecimal price, long quantity)
    {
        Order order = new Order(side, price, quantity);
        List<Trade> trades = orderBook.submitOrder(order);

        for(Trade trade : trades)
        {
            UUID e_buyid = trade.getBuyOrderID();
            UUID e_sellid = trade.getSellOrderID();
            BigDecimal e_Price = trade.getPrice();
            Long e_quantity = trade.getQuantity();
            Instant e_time = trade.getTimestamp();
            long e_seqNum = trade.getSequenceNum();

            TradeEntity entity = new TradeEntity(e_buyid,e_sellid,e_Price,e_quantity,e_time,e_seqNum);
            tradeRepository.save(entity);

            messagingTemplate.convertAndSend("/topic/trades", trade);
        }
        messagingTemplate.convertAndSend("/topic/book",orderBook.getBookDepth());

        return new PlaceOrderResult(order.getId(), trades);
    }

    
    public Optional<Order> cancelByID(UUID cancelid)
    {
        Optional<Order> cancelled = orderBook.cancelOrder(cancelid);
        cancelled.ifPresent(order -> messagingTemplate.convertAndSend("/topic/book", orderBook.getBookDepth()));
        return cancelled;
    }

    public OrderBook.BookDepth getBookDepth()
    {
        return orderBook.getBookDepth();
    }

    public List<TradeEntity> getAllTrades()
    {
        return tradeRepository.findAll();
    }
}
