package com.nicholasp.ordermatchingengine.engine;
import com.nicholasp.ordermatchingengine.model.*;
import java.math.*;
import java.util.*;

/**
 * A single-instrument limit order book that matches incoming orders against
 * resting orders using price-time priority.
 * <p>
 * Buy and sell orders are each kept in a {@link NavigableMap} from price to a
 * FIFO {@link Deque} of orders resting at that price. Buy prices are sorted
 * highest-first and sell prices lowest-first, so the best available price on
 * either side is always the map's first entry. A match exists when the buy
 * price is greater than or equal to the sell price; the trade executes at
 * the resting order's price, since that price was already committed to the
 * book before the incoming order arrived.
 */
public class OrderBook {
    private final NavigableMap<BigDecimal, Deque<Order>> buyOrders;
    private final NavigableMap<BigDecimal, Deque<Order>> sellOrders;

    public OrderBook()
    {
        this.buyOrders = new TreeMap<>(Comparator.reverseOrder());
        this.sellOrders = new TreeMap<>();
    }

    /**
     * Returns the book (buy or sell side) corresponding to the given side.
     */
    private NavigableMap<BigDecimal, Deque<Order>> getBookFor(OrderSide side)
    {
        if (side == OrderSide.BUY) {
            return buyOrders;
        } else {
            return sellOrders;
        }
    }

    /**
     * Determines whether the incoming order's price is compatible with the
     * best resting price on the opposite side of the book.
     */
    private boolean isMatch(Order incomingOrder, BigDecimal oppositePrice)
    {
        if (incomingOrder.getSide() == OrderSide.BUY) {
            return incomingOrder.getPrice().compareTo(oppositePrice) >= 0;
        } else {
            return incomingOrder.getPrice().compareTo(oppositePrice) <= 0;
        }
    }

    /**
     * Returns the order queue at the given book's best (first) price level.
     */
    private Deque<Order> getFirstOrderDeque(NavigableMap<BigDecimal, Deque<Order>> book)
    {
        return book.firstEntry().getValue();
    }

    /**
     * Adds an order to the back of its price level's queue, creating the
     * queue first if this is the first order at that price.
     */
    private void addToBook(NavigableMap<BigDecimal, Deque<Order>> book, Order order)
    {
        book.computeIfAbsent(order.getPrice(), price -> new ArrayDeque<>()).addLast(order);
    }

    /**
     * Submits an order to the book, matching it against resting orders on
     * the opposite side while a valid price match exists and quantity
     * remains. Any unfilled quantity is left resting on the order's own
     * side of the book.
     *
     * @param incomingOrder the order to submit
     * @return the trades generated by this submission, in execution order
     */
    public List<Trade> submitOrder(Order incomingOrder)
    {
        List<Trade> trades = new ArrayList<>();

        OrderSide own = incomingOrder.getSide();
        OrderSide opposite = own.opposite();

        // Keep matching against the opposite side's best price level as long as:
        // the incoming order still has quantity left, there's something to match
        // against, and the best opposite price is still compatible with our price.
        while (incomingOrder.getRemainingQuantity() > 0
                && !getBookFor(opposite).isEmpty()
                && isMatch(incomingOrder, getBookFor(opposite).firstEntry().getKey()))
        {
            // Oldest order at the opposite side's best price level (price-time priority).
            Order restingOrder = getFirstOrderDeque(getBookFor(opposite)).getFirst();

            // Fill as much as both orders can support; whichever runs out first caps the trade.
            long fillQty = Math.min(incomingOrder.getRemainingQuantity(), restingOrder.getRemainingQuantity());
            incomingOrder.fill(fillQty);
            restingOrder.fill(fillQty);

            // Route each order's ID to the correct slot in Trade's constructor,
            // since the incoming order isn't always the buyer.
            UUID buySideID;
            UUID sellSideID;
            if (own == OrderSide.BUY) {
                buySideID = incomingOrder.getId();
                sellSideID = restingOrder.getId();
            } else {
                buySideID = restingOrder.getId();
                sellSideID = incomingOrder.getId();
            }

            // Trade executes at the resting order's price - it was already committed
            // to the book, so the incoming (taker) order gets that price, not its own.
            Trade trade = new Trade(buySideID, sellSideID, restingOrder.getPrice(), fillQty);
            trades.add(trade);

            // Resting order fully consumed - pop it off the front of its queue.
            if (restingOrder.getRemainingQuantity() == 0) {
                getFirstOrderDeque(getBookFor(opposite)).pollFirst();
            }

            // That was the last order at this price level - drop the level from the map,
            // otherwise firstEntry() on the next loop would return an empty queue.
            if (getFirstOrderDeque(getBookFor(opposite)).isEmpty()) {
                getBookFor(opposite).pollFirstEntry();
            }
        }

        // Anything left unfilled (no match, or ran out of opposite orders) rests
        // on the incoming order's own side, waiting for a future counter-order.
        if (incomingOrder.getRemainingQuantity() > 0) {
            addToBook(getBookFor(own), incomingOrder);
        }

        return trades;
    }
}
