package com.nicholasp.ordermatchingengine.engine;

import com.nicholasp.ordermatchingengine.model.*;
import java.math.*;
import java.util.*;
import java.util.concurrent.locks.ReadWriteLock;
import java.util.concurrent.locks.ReentrantReadWriteLock;

/**
 * A single-instrument limit order book that matches incoming orders against
 * resting orders using price-time priority.
 * <p>
 * Buy and sell orders are each kept in a {@link NavigableMap} from price to a
 * FIFO {@link Deque} of orders resting at that price. Buy prices are sorted
 * highest-first and sell prices lowest-first, so the best available price on
 * either side is always the map's first entry. A match exists when the buy
 * price is greater than or equal to the sell price; the trade executes at
 * the resting order's price, since that price was already committed to the
 * book before the incoming order arrived.
 */
public class OrderBook {

    /**
     * One row of the book's depth view: a price and the total quantity
     * resting at that price, with no detail about which orders make it up.
     */
    public record PriceLevel(BigDecimal price, long totalQuantity) {
    }

    /**
     * A snapshot of the whole book's depth, both sides at once.
     */
    public record BookDepth(List<PriceLevel> buyLevels, List<PriceLevel> sellLevels) {
    }

    private final NavigableMap<BigDecimal, Deque<Order>> buyOrders;
    private final NavigableMap<BigDecimal, Deque<Order>> sellOrders;

    // Multiple readers (getBookDepth) may run concurrently; submitOrder/cancelOrder
    // need exclusive access since they mutate the same maps/deques.
    private final ReadWriteLock lock = new ReentrantReadWriteLock();

    public OrderBook() {
        this.buyOrders = new TreeMap<>(Comparator.reverseOrder());
        this.sellOrders = new TreeMap<>();
    }

    /**
     * Returns the book (buy or sell side) corresponding to the given side.
     */
    private NavigableMap<BigDecimal, Deque<Order>> getBookFor(OrderSide side) {
        if (side == OrderSide.BUY) {
            return buyOrders;
        } else {
            return sellOrders;
        }
    }

    /**
     * Determines whether the incoming order's price is compatible with the
     * best resting price on the opposite side of the book.
     */
    private boolean isMatch(Order incomingOrder, BigDecimal oppositePrice) {
        if (incomingOrder.getSide() == OrderSide.BUY) {
            return incomingOrder.getPrice().compareTo(oppositePrice) >= 0;
        } else {
            return incomingOrder.getPrice().compareTo(oppositePrice) <= 0;
        }
    }

    /**
     * Returns the order queue at the given book's best (first) price level.
     */
    private Deque<Order> getFirstOrderDeque(NavigableMap<BigDecimal, Deque<Order>> book) {
        return book.firstEntry().getValue();
    }

    /**
     * Adds an order to the back of its price level's queue, creating the
     * queue first if this is the first order at that price.
     */
    private void addToBook(NavigableMap<BigDecimal, Deque<Order>> book, Order order) {
        book.computeIfAbsent(order.getPrice(), price -> new ArrayDeque<>()).addLast(order);
    }

    /**
     * Submits an order to the book, matching it against resting orders on
     * the opposite side while a valid price match exists and quantity
     * remains. Any unfilled quantity is left resting on the order's own
     * side of the book.
     *
     * @param incomingOrder the order to submit
     * @return the trades generated by this submission, in execution order
     */

    public List<Trade> submitOrder(Order incomingOrder) {
        lock.writeLock().lock();
        try {
            List<Trade> trades = new ArrayList<>();

            OrderSide own = incomingOrder.getSide();
            OrderSide opposite = own.opposite();

            // Keep matching against the opposite side's best price level as long as:
            // the incoming order still has quantity left, there's something to match
            // against, and the best opposite price is still compatible with our price.
            while (incomingOrder.getRemainingQuantity() > 0
                    && !getBookFor(opposite).isEmpty()
                    && isMatch(incomingOrder, getBookFor(opposite).firstEntry().getKey())) {
                // Oldest order at the opposite side's best price level (price-time priority).
                Order restingOrder = getFirstOrderDeque(getBookFor(opposite)).getFirst();

                // Fill as much as both orders can support; whichever runs out first caps the
                // trade.
                long fillQty = Math.min(incomingOrder.getRemainingQuantity(), restingOrder.getRemainingQuantity());
                incomingOrder.fill(fillQty);
                restingOrder.fill(fillQty);

                // Route each order's ID to the correct slot in Trade's constructor,
                // since the incoming order isn't always the buyer.
                UUID buySideID;
                UUID sellSideID;
                if (own == OrderSide.BUY) {
                    buySideID = incomingOrder.getId();
                    sellSideID = restingOrder.getId();
                } else {
                    buySideID = restingOrder.getId();
                    sellSideID = incomingOrder.getId();
                }

                // Trade executes at the resting order's price - it was already committed
                // to the book, so the incoming (taker) order gets that price, not its own.
                Trade trade = new Trade(buySideID, sellSideID, restingOrder.getPrice(), fillQty);
                trades.add(trade);

                // Resting order fully consumed - pop it off the front of its queue.
                if (restingOrder.getRemainingQuantity() == 0) {
                    getFirstOrderDeque(getBookFor(opposite)).pollFirst();
                }

                // That was the last order at this price level - drop the level from the map,
                // otherwise firstEntry() on the next loop would return an empty queue.
                if (getFirstOrderDeque(getBookFor(opposite)).isEmpty()) {
                    getBookFor(opposite).pollFirstEntry();
                }
            }

            // Anything left unfilled (no match, or ran out of opposite orders) rests
            // on the incoming order's own side, waiting for a future counter-order.
            if (incomingOrder.getRemainingQuantity() > 0) {
                addToBook(getBookFor(own), incomingOrder);
            }

            return trades;
        } finally {
            lock.writeLock().unlock();
        }
    }

    public Optional<Order> cancelOrder(UUID cancelID) {
        lock.writeLock().lock();
        try {
            Iterator<Map.Entry<BigDecimal, Deque<Order>>> buyLevels = buyOrders.entrySet().iterator();
            Iterator<Map.Entry<BigDecimal, Deque<Order>>> sellLevels = sellOrders.entrySet().iterator();
            while (buyLevels.hasNext())// while the buyOrders has values (price levels) to iterator through
            {
                Map.Entry<BigDecimal, Deque<Order>> level = buyLevels.next(); // we get the level that we are traversing
                Iterator<Order> orders = level.getValue().iterator(); // iterator for orders
                while (orders.hasNext()) // while we have elements/orders to traverse
                {
                    Order order = orders.next(); // save the current one to a var to check parameter values
                    if (order.getId().equals(cancelID)) // if the current order's id is the same as the id that we want
                                                        // to cancel
                    {
                        orders.remove(); // we can safely remove that order
                        if (level.getValue().isEmpty()) // if the level that we are traversing no longer has elements in
                                                        // the deque of orders
                        {
                            buyLevels.remove(); // remove that level from the orderbook's respective side (in this case
                                                // buyorders)
                        }
                        return Optional.of(order); // return an Optional wrapped order
                    }
                }
            }

            while (sellLevels.hasNext()) {
                Map.Entry<BigDecimal, Deque<Order>> level = sellLevels.next();
                Iterator<Order> orders = level.getValue().iterator();
                while (orders.hasNext()) {
                    Order order = orders.next();
                    if (order.getId().equals(cancelID)) {
                        orders.remove();
                        if (level.getValue().isEmpty()) {
                            sellLevels.remove();
                        }
                        return Optional.of(order);
                    }
                }
            }

            return Optional.empty(); // return an empty Optional instance directly and handles the not found case

        } finally {
            lock.writeLock().unlock();
        }

    }

    public BookDepth getBookDepth() {
        lock.readLock().lock();
        try{
            List<PriceLevel> buyLevels = new ArrayList<>();
            List<PriceLevel> sellLevels = new ArrayList<>();
            Iterator<Map.Entry<BigDecimal, Deque<Order>>> buy = buyOrders.entrySet().iterator();
            Iterator<Map.Entry<BigDecimal, Deque<Order>>> sell = sellOrders.entrySet().iterator();

        while (buy.hasNext()) {
            Map.Entry<BigDecimal, Deque<Order>> level = buy.next();
            Iterator<Order> orders = level.getValue().iterator();
            long buyQuantity = 0;

            while (orders.hasNext()) {
                Order order = orders.next();
                buyQuantity += order.getRemainingQuantity();
            }
            buyLevels.add(new PriceLevel(level.getKey(), buyQuantity));
        }

        while (sell.hasNext()) {
            Map.Entry<BigDecimal, Deque<Order>> level = sell.next();
            Iterator<Order> orders = level.getValue().iterator();
            long sellQuantity = 0;
            while (orders.hasNext()) {
                Order order = orders.next();
                sellQuantity += order.getRemainingQuantity();
            }
            sellLevels.add(new PriceLevel(level.getKey(), sellQuantity));
        }

        return new BookDepth(buyLevels, sellLevels);
        
        } finally {
            lock.readLock().unlock();
        }
        
        
    }
}
